#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Monolito4am")]
	public partial class BasededatosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Inserttbl_foto_usuario(tbl_foto_usuario instance);
    partial void Updatetbl_foto_usuario(tbl_foto_usuario instance);
    partial void Deletetbl_foto_usuario(tbl_foto_usuario instance);
    partial void Inserttbl_imagen_producto(tbl_imagen_producto instance);
    partial void Updatetbl_imagen_producto(tbl_imagen_producto instance);
    partial void Deletetbl_imagen_producto(tbl_imagen_producto instance);
    partial void Inserttbl_producto(tbl_producto instance);
    partial void Updatetbl_producto(tbl_producto instance);
    partial void Deletetbl_producto(tbl_producto instance);
    partial void Inserttbl_proveedor(tbl_proveedor instance);
    partial void Updatetbl_proveedor(tbl_proveedor instance);
    partial void Deletetbl_proveedor(tbl_proveedor instance);
    partial void Inserttbl_recuperacion(tbl_recuperacion instance);
    partial void Updatetbl_recuperacion(tbl_recuperacion instance);
    partial void Deletetbl_recuperacion(tbl_recuperacion instance);
    partial void Inserttbl_tipo_usuario(tbl_tipo_usuario instance);
    partial void Updatetbl_tipo_usuario(tbl_tipo_usuario instance);
    partial void Deletetbl_tipo_usuario(tbl_tipo_usuario instance);
    partial void Inserttbl_usuario(tbl_usuario instance);
    partial void Updatetbl_usuario(tbl_usuario instance);
    partial void Deletetbl_usuario(tbl_usuario instance);
    #endregion
		
		public BasededatosDataContext() : 
				base(global::Capa_Datos.Properties.Settings.Default.Monolito4amConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BasededatosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BasededatosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BasededatosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BasededatosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_foto_usuario> tbl_foto_usuario
		{
			get
			{
				return this.GetTable<tbl_foto_usuario>();
			}
		}
		
		public System.Data.Linq.Table<tbl_imagen_producto> tbl_imagen_producto
		{
			get
			{
				return this.GetTable<tbl_imagen_producto>();
			}
		}
		
		public System.Data.Linq.Table<tbl_producto> tbl_producto
		{
			get
			{
				return this.GetTable<tbl_producto>();
			}
		}
		
		public System.Data.Linq.Table<tbl_proveedor> tbl_proveedor
		{
			get
			{
				return this.GetTable<tbl_proveedor>();
			}
		}
		
		public System.Data.Linq.Table<tbl_recuperacion> tbl_recuperacion
		{
			get
			{
				return this.GetTable<tbl_recuperacion>();
			}
		}
		
		public System.Data.Linq.Table<tbl_tipo_usuario> tbl_tipo_usuario
		{
			get
			{
				return this.GetTable<tbl_tipo_usuario>();
			}
		}
		
		public System.Data.Linq.Table<tbl_usuario> tbl_usuario
		{
			get
			{
				return this.GetTable<tbl_usuario>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.desencriptacon", IsComposable=true)]
		public string desencriptacon([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarBinary(MAX)")] System.Data.Linq.Binary clave)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), clave).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.encriptacon", IsComposable=true)]
		public System.Data.Linq.Binary encriptacon([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string clave)
		{
			return ((System.Data.Linq.Binary)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), clave).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_reset_intentos_si_nuevo_dia")]
		public int sp_reset_intentos_si_nuevo_dia()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ReiniciarIntentosDiarios")]
		public int sp_ReiniciarIntentosDiarios()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_login")]
		public int sp_login([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nick, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> resultado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] ref string mensaje)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nick, password, resultado, mensaje);
			resultado = ((System.Nullable<int>)(result.GetParameterValue(2)));
			mensaje = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_foto_usuario")]
	public partial class tbl_foto_usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _foto_id;
		
		private int _usu_id;
		
		private System.Data.Linq.Binary _foto_imagen;
		
		private string _foto_nombre;
		
		private string _foto_tipo;
		
		private System.Nullable<System.DateTime> _foto_fecha;
		
		private System.Nullable<char> _foto_principal;
		
		private EntityRef<tbl_usuario> _tbl_usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfoto_idChanging(int value);
    partial void Onfoto_idChanged();
    partial void Onusu_idChanging(int value);
    partial void Onusu_idChanged();
    partial void Onfoto_imagenChanging(System.Data.Linq.Binary value);
    partial void Onfoto_imagenChanged();
    partial void Onfoto_nombreChanging(string value);
    partial void Onfoto_nombreChanged();
    partial void Onfoto_tipoChanging(string value);
    partial void Onfoto_tipoChanged();
    partial void Onfoto_fechaChanging(System.Nullable<System.DateTime> value);
    partial void Onfoto_fechaChanged();
    partial void Onfoto_principalChanging(System.Nullable<char> value);
    partial void Onfoto_principalChanged();
    #endregion
		
		public tbl_foto_usuario()
		{
			this._tbl_usuario = default(EntityRef<tbl_usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int foto_id
		{
			get
			{
				return this._foto_id;
			}
			set
			{
				if ((this._foto_id != value))
				{
					this.Onfoto_idChanging(value);
					this.SendPropertyChanging();
					this._foto_id = value;
					this.SendPropertyChanged("foto_id");
					this.Onfoto_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_id", DbType="Int NOT NULL")]
		public int usu_id
		{
			get
			{
				return this._usu_id;
			}
			set
			{
				if ((this._usu_id != value))
				{
					if (this._tbl_usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onusu_idChanging(value);
					this.SendPropertyChanging();
					this._usu_id = value;
					this.SendPropertyChanged("usu_id");
					this.Onusu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto_imagen", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary foto_imagen
		{
			get
			{
				return this._foto_imagen;
			}
			set
			{
				if ((this._foto_imagen != value))
				{
					this.Onfoto_imagenChanging(value);
					this.SendPropertyChanging();
					this._foto_imagen = value;
					this.SendPropertyChanged("foto_imagen");
					this.Onfoto_imagenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto_nombre", DbType="VarChar(100)")]
		public string foto_nombre
		{
			get
			{
				return this._foto_nombre;
			}
			set
			{
				if ((this._foto_nombre != value))
				{
					this.Onfoto_nombreChanging(value);
					this.SendPropertyChanging();
					this._foto_nombre = value;
					this.SendPropertyChanged("foto_nombre");
					this.Onfoto_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto_tipo", DbType="VarChar(50)")]
		public string foto_tipo
		{
			get
			{
				return this._foto_tipo;
			}
			set
			{
				if ((this._foto_tipo != value))
				{
					this.Onfoto_tipoChanging(value);
					this.SendPropertyChanging();
					this._foto_tipo = value;
					this.SendPropertyChanged("foto_tipo");
					this.Onfoto_tipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto_fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> foto_fecha
		{
			get
			{
				return this._foto_fecha;
			}
			set
			{
				if ((this._foto_fecha != value))
				{
					this.Onfoto_fechaChanging(value);
					this.SendPropertyChanging();
					this._foto_fecha = value;
					this.SendPropertyChanged("foto_fecha");
					this.Onfoto_fechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto_principal", DbType="Char(1)")]
		public System.Nullable<char> foto_principal
		{
			get
			{
				return this._foto_principal;
			}
			set
			{
				if ((this._foto_principal != value))
				{
					this.Onfoto_principalChanging(value);
					this.SendPropertyChanging();
					this._foto_principal = value;
					this.SendPropertyChanged("foto_principal");
					this.Onfoto_principalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_usuario_tbl_foto_usuario", Storage="_tbl_usuario", ThisKey="usu_id", OtherKey="usu_id", IsForeignKey=true)]
		public tbl_usuario tbl_usuario
		{
			get
			{
				return this._tbl_usuario.Entity;
			}
			set
			{
				tbl_usuario previousValue = this._tbl_usuario.Entity;
				if (((previousValue != value) 
							|| (this._tbl_usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_usuario.Entity = null;
						previousValue.tbl_foto_usuario.Remove(this);
					}
					this._tbl_usuario.Entity = value;
					if ((value != null))
					{
						value.tbl_foto_usuario.Add(this);
						this._usu_id = value.usu_id;
					}
					else
					{
						this._usu_id = default(int);
					}
					this.SendPropertyChanged("tbl_usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_imagen_producto")]
	public partial class tbl_imagen_producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _img_id;
		
		private int _pro_id;
		
		private string _img_path;
		
		private string _img_nombre;
		
		private int _img_orden;
		
		private char _img_principal;
		
		private System.DateTime _img_fecha;
		
		private EntityRef<tbl_producto> _tbl_producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onimg_idChanging(int value);
    partial void Onimg_idChanged();
    partial void Onpro_idChanging(int value);
    partial void Onpro_idChanged();
    partial void Onimg_pathChanging(string value);
    partial void Onimg_pathChanged();
    partial void Onimg_nombreChanging(string value);
    partial void Onimg_nombreChanged();
    partial void Onimg_ordenChanging(int value);
    partial void Onimg_ordenChanged();
    partial void Onimg_principalChanging(char value);
    partial void Onimg_principalChanged();
    partial void Onimg_fechaChanging(System.DateTime value);
    partial void Onimg_fechaChanged();
    #endregion
		
		public tbl_imagen_producto()
		{
			this._tbl_producto = default(EntityRef<tbl_producto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int img_id
		{
			get
			{
				return this._img_id;
			}
			set
			{
				if ((this._img_id != value))
				{
					this.Onimg_idChanging(value);
					this.SendPropertyChanging();
					this._img_id = value;
					this.SendPropertyChanged("img_id");
					this.Onimg_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_id", DbType="Int NOT NULL")]
		public int pro_id
		{
			get
			{
				return this._pro_id;
			}
			set
			{
				if ((this._pro_id != value))
				{
					if (this._tbl_producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onpro_idChanging(value);
					this.SendPropertyChanging();
					this._pro_id = value;
					this.SendPropertyChanged("pro_id");
					this.Onpro_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img_path", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string img_path
		{
			get
			{
				return this._img_path;
			}
			set
			{
				if ((this._img_path != value))
				{
					this.Onimg_pathChanging(value);
					this.SendPropertyChanging();
					this._img_path = value;
					this.SendPropertyChanged("img_path");
					this.Onimg_pathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img_nombre", DbType="VarChar(100)")]
		public string img_nombre
		{
			get
			{
				return this._img_nombre;
			}
			set
			{
				if ((this._img_nombre != value))
				{
					this.Onimg_nombreChanging(value);
					this.SendPropertyChanging();
					this._img_nombre = value;
					this.SendPropertyChanged("img_nombre");
					this.Onimg_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img_orden", DbType="Int NOT NULL")]
		public int img_orden
		{
			get
			{
				return this._img_orden;
			}
			set
			{
				if ((this._img_orden != value))
				{
					this.Onimg_ordenChanging(value);
					this.SendPropertyChanging();
					this._img_orden = value;
					this.SendPropertyChanged("img_orden");
					this.Onimg_ordenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img_principal", DbType="Char(1) NOT NULL")]
		public char img_principal
		{
			get
			{
				return this._img_principal;
			}
			set
			{
				if ((this._img_principal != value))
				{
					this.Onimg_principalChanging(value);
					this.SendPropertyChanging();
					this._img_principal = value;
					this.SendPropertyChanged("img_principal");
					this.Onimg_principalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img_fecha", DbType="DateTime NOT NULL")]
		public System.DateTime img_fecha
		{
			get
			{
				return this._img_fecha;
			}
			set
			{
				if ((this._img_fecha != value))
				{
					this.Onimg_fechaChanging(value);
					this.SendPropertyChanging();
					this._img_fecha = value;
					this.SendPropertyChanged("img_fecha");
					this.Onimg_fechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_producto_tbl_imagen_producto", Storage="_tbl_producto", ThisKey="pro_id", OtherKey="pro_id", IsForeignKey=true)]
		public tbl_producto tbl_producto
		{
			get
			{
				return this._tbl_producto.Entity;
			}
			set
			{
				tbl_producto previousValue = this._tbl_producto.Entity;
				if (((previousValue != value) 
							|| (this._tbl_producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_producto.Entity = null;
						previousValue.tbl_imagen_producto.Remove(this);
					}
					this._tbl_producto.Entity = value;
					if ((value != null))
					{
						value.tbl_imagen_producto.Add(this);
						this._pro_id = value.pro_id;
					}
					else
					{
						this._pro_id = default(int);
					}
					this.SendPropertyChanged("tbl_producto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_producto")]
	public partial class tbl_producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pro_id;
		
		private string _pro_nombre;
		
		private System.Nullable<int> _pro_cantidad;
		
		private System.Nullable<decimal> _pro_precio;
		
		private System.Nullable<char> _pro_estado;
		
		private System.Nullable<int> _prov_id;
		
		private string _pro_imagen_path;
		
		private string _pro_categoria;
		
		private EntitySet<tbl_imagen_producto> _tbl_imagen_producto;
		
		private EntityRef<tbl_proveedor> _tbl_proveedor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpro_idChanging(int value);
    partial void Onpro_idChanged();
    partial void Onpro_nombreChanging(string value);
    partial void Onpro_nombreChanged();
    partial void Onpro_cantidadChanging(System.Nullable<int> value);
    partial void Onpro_cantidadChanged();
    partial void Onpro_precioChanging(System.Nullable<decimal> value);
    partial void Onpro_precioChanged();
    partial void Onpro_estadoChanging(System.Nullable<char> value);
    partial void Onpro_estadoChanged();
    partial void Onprov_idChanging(System.Nullable<int> value);
    partial void Onprov_idChanged();
    partial void Onpro_imagen_pathChanging(string value);
    partial void Onpro_imagen_pathChanged();
    partial void Onpro_categoriaChanging(string value);
    partial void Onpro_categoriaChanged();
    #endregion
		
		public tbl_producto()
		{
			this._tbl_imagen_producto = new EntitySet<tbl_imagen_producto>(new Action<tbl_imagen_producto>(this.attach_tbl_imagen_producto), new Action<tbl_imagen_producto>(this.detach_tbl_imagen_producto));
			this._tbl_proveedor = default(EntityRef<tbl_proveedor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pro_id
		{
			get
			{
				return this._pro_id;
			}
			set
			{
				if ((this._pro_id != value))
				{
					this.Onpro_idChanging(value);
					this.SendPropertyChanging();
					this._pro_id = value;
					this.SendPropertyChanged("pro_id");
					this.Onpro_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_nombre", DbType="VarChar(50)")]
		public string pro_nombre
		{
			get
			{
				return this._pro_nombre;
			}
			set
			{
				if ((this._pro_nombre != value))
				{
					this.Onpro_nombreChanging(value);
					this.SendPropertyChanging();
					this._pro_nombre = value;
					this.SendPropertyChanged("pro_nombre");
					this.Onpro_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_cantidad", DbType="Int")]
		public System.Nullable<int> pro_cantidad
		{
			get
			{
				return this._pro_cantidad;
			}
			set
			{
				if ((this._pro_cantidad != value))
				{
					this.Onpro_cantidadChanging(value);
					this.SendPropertyChanging();
					this._pro_cantidad = value;
					this.SendPropertyChanged("pro_cantidad");
					this.Onpro_cantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_precio", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> pro_precio
		{
			get
			{
				return this._pro_precio;
			}
			set
			{
				if ((this._pro_precio != value))
				{
					this.Onpro_precioChanging(value);
					this.SendPropertyChanging();
					this._pro_precio = value;
					this.SendPropertyChanged("pro_precio");
					this.Onpro_precioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_estado", DbType="Char(1)")]
		public System.Nullable<char> pro_estado
		{
			get
			{
				return this._pro_estado;
			}
			set
			{
				if ((this._pro_estado != value))
				{
					this.Onpro_estadoChanging(value);
					this.SendPropertyChanging();
					this._pro_estado = value;
					this.SendPropertyChanged("pro_estado");
					this.Onpro_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_id", DbType="Int")]
		public System.Nullable<int> prov_id
		{
			get
			{
				return this._prov_id;
			}
			set
			{
				if ((this._prov_id != value))
				{
					if (this._tbl_proveedor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onprov_idChanging(value);
					this.SendPropertyChanging();
					this._prov_id = value;
					this.SendPropertyChanged("prov_id");
					this.Onprov_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_imagen_path", DbType="VarChar(255)")]
		public string pro_imagen_path
		{
			get
			{
				return this._pro_imagen_path;
			}
			set
			{
				if ((this._pro_imagen_path != value))
				{
					this.Onpro_imagen_pathChanging(value);
					this.SendPropertyChanging();
					this._pro_imagen_path = value;
					this.SendPropertyChanged("pro_imagen_path");
					this.Onpro_imagen_pathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_categoria", DbType="VarChar(50)")]
		public string pro_categoria
		{
			get
			{
				return this._pro_categoria;
			}
			set
			{
				if ((this._pro_categoria != value))
				{
					this.Onpro_categoriaChanging(value);
					this.SendPropertyChanging();
					this._pro_categoria = value;
					this.SendPropertyChanged("pro_categoria");
					this.Onpro_categoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_producto_tbl_imagen_producto", Storage="_tbl_imagen_producto", ThisKey="pro_id", OtherKey="pro_id")]
		public EntitySet<tbl_imagen_producto> tbl_imagen_producto
		{
			get
			{
				return this._tbl_imagen_producto;
			}
			set
			{
				this._tbl_imagen_producto.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_proveedor_tbl_producto", Storage="_tbl_proveedor", ThisKey="prov_id", OtherKey="prov_id", IsForeignKey=true)]
		public tbl_proveedor tbl_proveedor
		{
			get
			{
				return this._tbl_proveedor.Entity;
			}
			set
			{
				tbl_proveedor previousValue = this._tbl_proveedor.Entity;
				if (((previousValue != value) 
							|| (this._tbl_proveedor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_proveedor.Entity = null;
						previousValue.tbl_producto.Remove(this);
					}
					this._tbl_proveedor.Entity = value;
					if ((value != null))
					{
						value.tbl_producto.Add(this);
						this._prov_id = value.prov_id;
					}
					else
					{
						this._prov_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_proveedor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_imagen_producto(tbl_imagen_producto entity)
		{
			this.SendPropertyChanging();
			entity.tbl_producto = this;
		}
		
		private void detach_tbl_imagen_producto(tbl_imagen_producto entity)
		{
			this.SendPropertyChanging();
			entity.tbl_producto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_proveedor")]
	public partial class tbl_proveedor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _prov_id;
		
		private string _prov_nombre;
		
		private System.Nullable<char> _prov_estado;
		
		private EntitySet<tbl_producto> _tbl_producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onprov_idChanging(int value);
    partial void Onprov_idChanged();
    partial void Onprov_nombreChanging(string value);
    partial void Onprov_nombreChanged();
    partial void Onprov_estadoChanging(System.Nullable<char> value);
    partial void Onprov_estadoChanged();
    #endregion
		
		public tbl_proveedor()
		{
			this._tbl_producto = new EntitySet<tbl_producto>(new Action<tbl_producto>(this.attach_tbl_producto), new Action<tbl_producto>(this.detach_tbl_producto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int prov_id
		{
			get
			{
				return this._prov_id;
			}
			set
			{
				if ((this._prov_id != value))
				{
					this.Onprov_idChanging(value);
					this.SendPropertyChanging();
					this._prov_id = value;
					this.SendPropertyChanged("prov_id");
					this.Onprov_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_nombre", DbType="VarChar(50)")]
		public string prov_nombre
		{
			get
			{
				return this._prov_nombre;
			}
			set
			{
				if ((this._prov_nombre != value))
				{
					this.Onprov_nombreChanging(value);
					this.SendPropertyChanging();
					this._prov_nombre = value;
					this.SendPropertyChanged("prov_nombre");
					this.Onprov_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_estado", DbType="Char(1)")]
		public System.Nullable<char> prov_estado
		{
			get
			{
				return this._prov_estado;
			}
			set
			{
				if ((this._prov_estado != value))
				{
					this.Onprov_estadoChanging(value);
					this.SendPropertyChanging();
					this._prov_estado = value;
					this.SendPropertyChanged("prov_estado");
					this.Onprov_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_proveedor_tbl_producto", Storage="_tbl_producto", ThisKey="prov_id", OtherKey="prov_id")]
		public EntitySet<tbl_producto> tbl_producto
		{
			get
			{
				return this._tbl_producto;
			}
			set
			{
				this._tbl_producto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_producto(tbl_producto entity)
		{
			this.SendPropertyChanging();
			entity.tbl_proveedor = this;
		}
		
		private void detach_tbl_producto(tbl_producto entity)
		{
			this.SendPropertyChanging();
			entity.tbl_proveedor = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_recuperacion")]
	public partial class tbl_recuperacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _rec_id;
		
		private System.Nullable<int> _usu_id;
		
		private string _rec_token;
		
		private System.Nullable<System.DateTime> _rec_expira;
		
		private System.Nullable<char> _rec_usado;
		
		private EntityRef<tbl_usuario> _tbl_usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onrec_idChanging(int value);
    partial void Onrec_idChanged();
    partial void Onusu_idChanging(System.Nullable<int> value);
    partial void Onusu_idChanged();
    partial void Onrec_tokenChanging(string value);
    partial void Onrec_tokenChanged();
    partial void Onrec_expiraChanging(System.Nullable<System.DateTime> value);
    partial void Onrec_expiraChanged();
    partial void Onrec_usadoChanging(System.Nullable<char> value);
    partial void Onrec_usadoChanged();
    #endregion
		
		public tbl_recuperacion()
		{
			this._tbl_usuario = default(EntityRef<tbl_usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rec_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int rec_id
		{
			get
			{
				return this._rec_id;
			}
			set
			{
				if ((this._rec_id != value))
				{
					this.Onrec_idChanging(value);
					this.SendPropertyChanging();
					this._rec_id = value;
					this.SendPropertyChanged("rec_id");
					this.Onrec_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_id", DbType="Int")]
		public System.Nullable<int> usu_id
		{
			get
			{
				return this._usu_id;
			}
			set
			{
				if ((this._usu_id != value))
				{
					if (this._tbl_usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onusu_idChanging(value);
					this.SendPropertyChanging();
					this._usu_id = value;
					this.SendPropertyChanged("usu_id");
					this.Onusu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rec_token", DbType="VarChar(20)")]
		public string rec_token
		{
			get
			{
				return this._rec_token;
			}
			set
			{
				if ((this._rec_token != value))
				{
					this.Onrec_tokenChanging(value);
					this.SendPropertyChanging();
					this._rec_token = value;
					this.SendPropertyChanged("rec_token");
					this.Onrec_tokenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rec_expira", DbType="DateTime")]
		public System.Nullable<System.DateTime> rec_expira
		{
			get
			{
				return this._rec_expira;
			}
			set
			{
				if ((this._rec_expira != value))
				{
					this.Onrec_expiraChanging(value);
					this.SendPropertyChanging();
					this._rec_expira = value;
					this.SendPropertyChanged("rec_expira");
					this.Onrec_expiraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rec_usado", DbType="Char(1)")]
		public System.Nullable<char> rec_usado
		{
			get
			{
				return this._rec_usado;
			}
			set
			{
				if ((this._rec_usado != value))
				{
					this.Onrec_usadoChanging(value);
					this.SendPropertyChanging();
					this._rec_usado = value;
					this.SendPropertyChanged("rec_usado");
					this.Onrec_usadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_usuario_tbl_recuperacion", Storage="_tbl_usuario", ThisKey="usu_id", OtherKey="usu_id", IsForeignKey=true)]
		public tbl_usuario tbl_usuario
		{
			get
			{
				return this._tbl_usuario.Entity;
			}
			set
			{
				tbl_usuario previousValue = this._tbl_usuario.Entity;
				if (((previousValue != value) 
							|| (this._tbl_usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_usuario.Entity = null;
						previousValue.tbl_recuperacion.Remove(this);
					}
					this._tbl_usuario.Entity = value;
					if ((value != null))
					{
						value.tbl_recuperacion.Add(this);
						this._usu_id = value.usu_id;
					}
					else
					{
						this._usu_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_tipo_usuario")]
	public partial class tbl_tipo_usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _tusu_id;
		
		private string _tusu_nombre;
		
		private System.Nullable<char> _tusu_estado;
		
		private EntitySet<tbl_usuario> _tbl_usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontusu_idChanging(int value);
    partial void Ontusu_idChanged();
    partial void Ontusu_nombreChanging(string value);
    partial void Ontusu_nombreChanged();
    partial void Ontusu_estadoChanging(System.Nullable<char> value);
    partial void Ontusu_estadoChanged();
    #endregion
		
		public tbl_tipo_usuario()
		{
			this._tbl_usuario = new EntitySet<tbl_usuario>(new Action<tbl_usuario>(this.attach_tbl_usuario), new Action<tbl_usuario>(this.detach_tbl_usuario));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tusu_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int tusu_id
		{
			get
			{
				return this._tusu_id;
			}
			set
			{
				if ((this._tusu_id != value))
				{
					this.Ontusu_idChanging(value);
					this.SendPropertyChanging();
					this._tusu_id = value;
					this.SendPropertyChanged("tusu_id");
					this.Ontusu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tusu_nombre", DbType="VarChar(50)")]
		public string tusu_nombre
		{
			get
			{
				return this._tusu_nombre;
			}
			set
			{
				if ((this._tusu_nombre != value))
				{
					this.Ontusu_nombreChanging(value);
					this.SendPropertyChanging();
					this._tusu_nombre = value;
					this.SendPropertyChanged("tusu_nombre");
					this.Ontusu_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tusu_estado", DbType="Char(1)")]
		public System.Nullable<char> tusu_estado
		{
			get
			{
				return this._tusu_estado;
			}
			set
			{
				if ((this._tusu_estado != value))
				{
					this.Ontusu_estadoChanging(value);
					this.SendPropertyChanging();
					this._tusu_estado = value;
					this.SendPropertyChanged("tusu_estado");
					this.Ontusu_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_tipo_usuario_tbl_usuario", Storage="_tbl_usuario", ThisKey="tusu_id", OtherKey="tusu_id")]
		public EntitySet<tbl_usuario> tbl_usuario
		{
			get
			{
				return this._tbl_usuario;
			}
			set
			{
				this._tbl_usuario.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_usuario(tbl_usuario entity)
		{
			this.SendPropertyChanging();
			entity.tbl_tipo_usuario = this;
		}
		
		private void detach_tbl_usuario(tbl_usuario entity)
		{
			this.SendPropertyChanging();
			entity.tbl_tipo_usuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_usuario")]
	public partial class tbl_usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _usu_id;
		
		private string _usu_cedula;
		
		private string _usu_nombres;
		
		private string _usu_apellidos;
		
		private string _usu_direccion;
		
		private string _usu_celular;
		
		private string _usu_correo;
		
		private System.Nullable<System.DateTime> _usu_fecha_creacion;
		
		private System.Nullable<System.DateTime> _usu_fecha_cumple;
		
		private string _usu_nick;
		
		private System.Data.Linq.Binary _usu_contraseña;
		
		private System.Nullable<int> _usu_intentos;
		
		private string _usu_codigo_OTP;
		
		private System.Nullable<char> _usu_estado;
		
		private System.Nullable<int> _tusu_id;
		
		private System.Nullable<System.DateTime> _usu_fecha_ultimo_intento;
		
		private EntitySet<tbl_foto_usuario> _tbl_foto_usuario;
		
		private EntitySet<tbl_recuperacion> _tbl_recuperacion;
		
		private EntityRef<tbl_tipo_usuario> _tbl_tipo_usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onusu_idChanging(int value);
    partial void Onusu_idChanged();
    partial void Onusu_cedulaChanging(string value);
    partial void Onusu_cedulaChanged();
    partial void Onusu_nombresChanging(string value);
    partial void Onusu_nombresChanged();
    partial void Onusu_apellidosChanging(string value);
    partial void Onusu_apellidosChanged();
    partial void Onusu_direccionChanging(string value);
    partial void Onusu_direccionChanged();
    partial void Onusu_celularChanging(string value);
    partial void Onusu_celularChanged();
    partial void Onusu_correoChanging(string value);
    partial void Onusu_correoChanged();
    partial void Onusu_fecha_creacionChanging(System.Nullable<System.DateTime> value);
    partial void Onusu_fecha_creacionChanged();
    partial void Onusu_fecha_cumpleChanging(System.Nullable<System.DateTime> value);
    partial void Onusu_fecha_cumpleChanged();
    partial void Onusu_nickChanging(string value);
    partial void Onusu_nickChanged();
    partial void Onusu_contraseñaChanging(System.Data.Linq.Binary value);
    partial void Onusu_contraseñaChanged();
    partial void Onusu_intentosChanging(System.Nullable<int> value);
    partial void Onusu_intentosChanged();
    partial void Onusu_codigo_OTPChanging(string value);
    partial void Onusu_codigo_OTPChanged();
    partial void Onusu_estadoChanging(System.Nullable<char> value);
    partial void Onusu_estadoChanged();
    partial void Ontusu_idChanging(System.Nullable<int> value);
    partial void Ontusu_idChanged();
    partial void Onusu_fecha_ultimo_intentoChanging(System.Nullable<System.DateTime> value);
    partial void Onusu_fecha_ultimo_intentoChanged();
    #endregion
		
		public tbl_usuario()
		{
			this._tbl_foto_usuario = new EntitySet<tbl_foto_usuario>(new Action<tbl_foto_usuario>(this.attach_tbl_foto_usuario), new Action<tbl_foto_usuario>(this.detach_tbl_foto_usuario));
			this._tbl_recuperacion = new EntitySet<tbl_recuperacion>(new Action<tbl_recuperacion>(this.attach_tbl_recuperacion), new Action<tbl_recuperacion>(this.detach_tbl_recuperacion));
			this._tbl_tipo_usuario = default(EntityRef<tbl_tipo_usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int usu_id
		{
			get
			{
				return this._usu_id;
			}
			set
			{
				if ((this._usu_id != value))
				{
					this.Onusu_idChanging(value);
					this.SendPropertyChanging();
					this._usu_id = value;
					this.SendPropertyChanged("usu_id");
					this.Onusu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_cedula", DbType="VarChar(10)")]
		public string usu_cedula
		{
			get
			{
				return this._usu_cedula;
			}
			set
			{
				if ((this._usu_cedula != value))
				{
					this.Onusu_cedulaChanging(value);
					this.SendPropertyChanging();
					this._usu_cedula = value;
					this.SendPropertyChanged("usu_cedula");
					this.Onusu_cedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_nombres", DbType="VarChar(50)")]
		public string usu_nombres
		{
			get
			{
				return this._usu_nombres;
			}
			set
			{
				if ((this._usu_nombres != value))
				{
					this.Onusu_nombresChanging(value);
					this.SendPropertyChanging();
					this._usu_nombres = value;
					this.SendPropertyChanged("usu_nombres");
					this.Onusu_nombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_apellidos", DbType="VarChar(50)")]
		public string usu_apellidos
		{
			get
			{
				return this._usu_apellidos;
			}
			set
			{
				if ((this._usu_apellidos != value))
				{
					this.Onusu_apellidosChanging(value);
					this.SendPropertyChanging();
					this._usu_apellidos = value;
					this.SendPropertyChanged("usu_apellidos");
					this.Onusu_apellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_direccion", DbType="VarChar(50)")]
		public string usu_direccion
		{
			get
			{
				return this._usu_direccion;
			}
			set
			{
				if ((this._usu_direccion != value))
				{
					this.Onusu_direccionChanging(value);
					this.SendPropertyChanging();
					this._usu_direccion = value;
					this.SendPropertyChanged("usu_direccion");
					this.Onusu_direccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_celular", DbType="VarChar(10)")]
		public string usu_celular
		{
			get
			{
				return this._usu_celular;
			}
			set
			{
				if ((this._usu_celular != value))
				{
					this.Onusu_celularChanging(value);
					this.SendPropertyChanging();
					this._usu_celular = value;
					this.SendPropertyChanged("usu_celular");
					this.Onusu_celularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_correo", DbType="VarChar(150)")]
		public string usu_correo
		{
			get
			{
				return this._usu_correo;
			}
			set
			{
				if ((this._usu_correo != value))
				{
					this.Onusu_correoChanging(value);
					this.SendPropertyChanging();
					this._usu_correo = value;
					this.SendPropertyChanged("usu_correo");
					this.Onusu_correoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_fecha_creacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> usu_fecha_creacion
		{
			get
			{
				return this._usu_fecha_creacion;
			}
			set
			{
				if ((this._usu_fecha_creacion != value))
				{
					this.Onusu_fecha_creacionChanging(value);
					this.SendPropertyChanging();
					this._usu_fecha_creacion = value;
					this.SendPropertyChanged("usu_fecha_creacion");
					this.Onusu_fecha_creacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_fecha_cumple", DbType="Date")]
		public System.Nullable<System.DateTime> usu_fecha_cumple
		{
			get
			{
				return this._usu_fecha_cumple;
			}
			set
			{
				if ((this._usu_fecha_cumple != value))
				{
					this.Onusu_fecha_cumpleChanging(value);
					this.SendPropertyChanging();
					this._usu_fecha_cumple = value;
					this.SendPropertyChanged("usu_fecha_cumple");
					this.Onusu_fecha_cumpleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_nick", DbType="VarChar(50)")]
		public string usu_nick
		{
			get
			{
				return this._usu_nick;
			}
			set
			{
				if ((this._usu_nick != value))
				{
					this.Onusu_nickChanging(value);
					this.SendPropertyChanging();
					this._usu_nick = value;
					this.SendPropertyChanged("usu_nick");
					this.Onusu_nickChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_contraseña", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary usu_contraseña
		{
			get
			{
				return this._usu_contraseña;
			}
			set
			{
				if ((this._usu_contraseña != value))
				{
					this.Onusu_contraseñaChanging(value);
					this.SendPropertyChanging();
					this._usu_contraseña = value;
					this.SendPropertyChanged("usu_contraseña");
					this.Onusu_contraseñaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_intentos", DbType="Int")]
		public System.Nullable<int> usu_intentos
		{
			get
			{
				return this._usu_intentos;
			}
			set
			{
				if ((this._usu_intentos != value))
				{
					this.Onusu_intentosChanging(value);
					this.SendPropertyChanging();
					this._usu_intentos = value;
					this.SendPropertyChanged("usu_intentos");
					this.Onusu_intentosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_codigo_OTP", DbType="VarChar(10)")]
		public string usu_codigo_OTP
		{
			get
			{
				return this._usu_codigo_OTP;
			}
			set
			{
				if ((this._usu_codigo_OTP != value))
				{
					this.Onusu_codigo_OTPChanging(value);
					this.SendPropertyChanging();
					this._usu_codigo_OTP = value;
					this.SendPropertyChanged("usu_codigo_OTP");
					this.Onusu_codigo_OTPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_estado", DbType="Char(1)")]
		public System.Nullable<char> usu_estado
		{
			get
			{
				return this._usu_estado;
			}
			set
			{
				if ((this._usu_estado != value))
				{
					this.Onusu_estadoChanging(value);
					this.SendPropertyChanging();
					this._usu_estado = value;
					this.SendPropertyChanged("usu_estado");
					this.Onusu_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tusu_id", DbType="Int")]
		public System.Nullable<int> tusu_id
		{
			get
			{
				return this._tusu_id;
			}
			set
			{
				if ((this._tusu_id != value))
				{
					if (this._tbl_tipo_usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ontusu_idChanging(value);
					this.SendPropertyChanging();
					this._tusu_id = value;
					this.SendPropertyChanged("tusu_id");
					this.Ontusu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_fecha_ultimo_intento", DbType="DateTime")]
		public System.Nullable<System.DateTime> usu_fecha_ultimo_intento
		{
			get
			{
				return this._usu_fecha_ultimo_intento;
			}
			set
			{
				if ((this._usu_fecha_ultimo_intento != value))
				{
					this.Onusu_fecha_ultimo_intentoChanging(value);
					this.SendPropertyChanging();
					this._usu_fecha_ultimo_intento = value;
					this.SendPropertyChanged("usu_fecha_ultimo_intento");
					this.Onusu_fecha_ultimo_intentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_usuario_tbl_foto_usuario", Storage="_tbl_foto_usuario", ThisKey="usu_id", OtherKey="usu_id")]
		public EntitySet<tbl_foto_usuario> tbl_foto_usuario
		{
			get
			{
				return this._tbl_foto_usuario;
			}
			set
			{
				this._tbl_foto_usuario.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_usuario_tbl_recuperacion", Storage="_tbl_recuperacion", ThisKey="usu_id", OtherKey="usu_id")]
		public EntitySet<tbl_recuperacion> tbl_recuperacion
		{
			get
			{
				return this._tbl_recuperacion;
			}
			set
			{
				this._tbl_recuperacion.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_tipo_usuario_tbl_usuario", Storage="_tbl_tipo_usuario", ThisKey="tusu_id", OtherKey="tusu_id", IsForeignKey=true)]
		public tbl_tipo_usuario tbl_tipo_usuario
		{
			get
			{
				return this._tbl_tipo_usuario.Entity;
			}
			set
			{
				tbl_tipo_usuario previousValue = this._tbl_tipo_usuario.Entity;
				if (((previousValue != value) 
							|| (this._tbl_tipo_usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_tipo_usuario.Entity = null;
						previousValue.tbl_usuario.Remove(this);
					}
					this._tbl_tipo_usuario.Entity = value;
					if ((value != null))
					{
						value.tbl_usuario.Add(this);
						this._tusu_id = value.tusu_id;
					}
					else
					{
						this._tusu_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_tipo_usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_foto_usuario(tbl_foto_usuario entity)
		{
			this.SendPropertyChanging();
			entity.tbl_usuario = this;
		}
		
		private void detach_tbl_foto_usuario(tbl_foto_usuario entity)
		{
			this.SendPropertyChanging();
			entity.tbl_usuario = null;
		}
		
		private void attach_tbl_recuperacion(tbl_recuperacion entity)
		{
			this.SendPropertyChanging();
			entity.tbl_usuario = this;
		}
		
		private void detach_tbl_recuperacion(tbl_recuperacion entity)
		{
			this.SendPropertyChanging();
			entity.tbl_usuario = null;
		}
	}
}
#pragma warning restore 1591
