<?xml version="1.0" encoding="utf-8"?><Database Name="Monolito4am" Class="BasededatosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=Monolito4am;Integrated Security=True;Encrypt=False" SettingsObjectName="Capa_Datos.Properties.Settings" SettingsPropertyName="Monolito4amConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_foto_usuario" Member="tbl_foto_usuario">
    <Type Name="tbl_foto_usuario">
      <Column Name="foto_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="usu_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="foto_imagen" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="foto_nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="foto_tipo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="foto_fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="foto_principal" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Association Name="tbl_usuario_tbl_foto_usuario" Member="tbl_usuario" ThisKey="usu_id" OtherKey="usu_id" Type="tbl_usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_imagen_producto" Member="tbl_imagen_producto">
    <Type Name="tbl_imagen_producto">
      <Column Name="img_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="pro_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="img_path" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="img_nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="img_orden" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="img_principal" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="img_fecha" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="tbl_producto_tbl_imagen_producto" Member="tbl_producto" ThisKey="pro_id" OtherKey="pro_id" Type="tbl_producto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_producto" Member="tbl_producto">
    <Type Name="tbl_producto">
      <Column Name="pro_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="pro_nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="pro_cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="pro_precio" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="pro_estado" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="prov_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="pro_imagen_path" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="pro_categoria" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="tbl_producto_tbl_imagen_producto" Member="tbl_imagen_producto" ThisKey="pro_id" OtherKey="pro_id" Type="tbl_imagen_producto" />
      <Association Name="tbl_proveedor_tbl_producto" Member="tbl_proveedor" ThisKey="prov_id" OtherKey="prov_id" Type="tbl_proveedor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_proveedor" Member="tbl_proveedor">
    <Type Name="tbl_proveedor">
      <Column Name="prov_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="prov_nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="prov_estado" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Association Name="tbl_proveedor_tbl_producto" Member="tbl_producto" ThisKey="prov_id" OtherKey="prov_id" Type="tbl_producto" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_recuperacion" Member="tbl_recuperacion">
    <Type Name="tbl_recuperacion">
      <Column Name="rec_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="usu_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="rec_token" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="rec_expira" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="rec_usado" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Association Name="tbl_usuario_tbl_recuperacion" Member="tbl_usuario" ThisKey="usu_id" OtherKey="usu_id" Type="tbl_usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_tipo_usuario" Member="tbl_tipo_usuario">
    <Type Name="tbl_tipo_usuario">
      <Column Name="tusu_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tusu_nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tusu_estado" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Association Name="tbl_tipo_usuario_tbl_usuario" Member="tbl_usuario" ThisKey="tusu_id" OtherKey="tusu_id" Type="tbl_usuario" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_usuario" Member="tbl_usuario">
    <Type Name="tbl_usuario">
      <Column Name="usu_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="usu_cedula" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="usu_nombres" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="usu_apellidos" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="usu_direccion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="usu_celular" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="usu_correo" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="usu_fecha_creacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="usu_fecha_cumple" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="usu_nick" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="usu_contraseña" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="usu_intentos" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="usu_codigo_OTP" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="usu_estado" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="tusu_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="usu_fecha_ultimo_intento" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="tbl_usuario_tbl_foto_usuario" Member="tbl_foto_usuario" ThisKey="usu_id" OtherKey="usu_id" Type="tbl_foto_usuario" />
      <Association Name="tbl_usuario_tbl_recuperacion" Member="tbl_recuperacion" ThisKey="usu_id" OtherKey="usu_id" Type="tbl_recuperacion" />
      <Association Name="tbl_tipo_usuario_tbl_usuario" Member="tbl_tipo_usuario" ThisKey="tusu_id" OtherKey="tusu_id" Type="tbl_tipo_usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.desencriptacon" Method="desencriptacon" IsComposable="true">
    <Parameter Name="clave" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.encriptacon" Method="encriptacon" IsComposable="true">
    <Parameter Name="clave" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Data.Linq.Binary" />
  </Function>
  <Function Name="dbo.sp_reset_intentos_si_nuevo_dia" Method="sp_reset_intentos_si_nuevo_dia">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ReiniciarIntentosDiarios" Method="sp_ReiniciarIntentosDiarios">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_login" Method="sp_login">
    <Parameter Name="nick" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="resultado" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="mensaje" Type="System.String" DbType="VarChar(200)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>