//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado manualmente para Imagenes.aspx
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monolito4b.Mantenimiento
{
    public partial class Imagenes
    {
        protected global::System.Web.UI.WebControls.DropDownList ddlProducto;
        protected global::System.Web.UI.WebControls.TextBox txtOrden;
        protected global::System.Web.UI.WebControls.DropDownList ddlPrincipal;
        protected global::System.Web.UI.WebControls.Button btnSubir;
        protected global::System.Web.UI.WebControls.Label lblMsg;

        // Paso 2 — confirmación
        protected global::System.Web.UI.WebControls.HiddenField hfTempPaths;
        protected global::System.Web.UI.WebControls.HiddenField hfTempNombres;
        protected global::System.Web.UI.WebControls.Panel pnlConfirmar;
        protected global::System.Web.UI.WebControls.Repeater rptTemp;
        protected global::System.Web.UI.WebControls.Button btnConfirmar;
        protected global::System.Web.UI.WebControls.Button btnDescartarTodo;

        // Galería
        protected global::System.Web.UI.UpdatePanel upFiltro;
        protected global::System.Web.UI.WebControls.TextBox txtFiltro;
        protected global::System.Web.UI.UpdatePanel upGaleria;
        protected global::System.Web.UI.WebControls.Repeater rptImagenes;
        protected global::System.Web.UI.WebControls.Literal litVacio;
        protected global::System.Web.UI.WebControls.HyperLink hlExcel;
    }
}
