//------------------------------------------------------------------------------
// <auto-generated>
//     Codigo generado manualmente para Usu.aspx
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monolito4b.Mantenimiento
{
    public partial class Usu
    {
        protected global::System.Web.UI.UpdatePanel upTodo;
        protected global::System.Web.UI.WebControls.Literal litTituloForm;
        protected global::System.Web.UI.WebControls.HiddenField hfUserId;

        // Paneles de modo
        protected global::System.Web.UI.WebControls.Panel pnlAvisoEdicion;
        protected global::System.Web.UI.WebControls.Panel pnlInfoReadonly;
        protected global::System.Web.UI.WebControls.Panel pnlCamposCreacion;

        // Literales de solo lectura
        protected global::System.Web.UI.WebControls.Literal litRoCedula;
        protected global::System.Web.UI.WebControls.Literal litRoNombres;
        protected global::System.Web.UI.WebControls.Literal litRoApellidos;
        protected global::System.Web.UI.WebControls.Literal litRoNick;
        protected global::System.Web.UI.WebControls.Literal litRoCorreo;
        protected global::System.Web.UI.WebControls.Literal litRoCelular;

        // Campos de creacion
        protected global::System.Web.UI.WebControls.TextBox txtCedula;
        protected global::System.Web.UI.WebControls.TextBox txtNombres;
        protected global::System.Web.UI.WebControls.TextBox txtApellidos;
        protected global::System.Web.UI.WebControls.TextBox txtCelular;
        protected global::System.Web.UI.WebControls.TextBox txtCorreo;
        protected global::System.Web.UI.WebControls.TextBox txtNick;
        protected global::System.Web.UI.WebControls.TextBox txtPassword;

        // Campos siempre editables
        protected global::System.Web.UI.WebControls.TextBox txtDireccion;
        protected global::System.Web.UI.WebControls.DropDownList ddlTipo;
        protected global::System.Web.UI.WebControls.DropDownList ddlEstadoUsu;

        protected global::System.Web.UI.WebControls.Button btnGuardarUsu;
        protected global::System.Web.UI.WebControls.Button btnCancelarUsu;
        protected global::System.Web.UI.WebControls.Label lblMsgUsu;
        protected global::System.Web.UI.WebControls.TextBox txtBuscarUsu;
        protected global::System.Web.UI.WebControls.GridView gvUsuarios;
    }
}
